package gridgames;

/**
 * Interface that a class must implement to be able to be a listener
 * of a {@link Game} object.
 * <p>
 * {@code GameListener} objects can be attached to a {@code Game} instance with
 * the method {@link Game#addListener(GameListener)}. Added listeners are able
 * to receive notifications for various types of events happening during the
 * game, through the {@code Game} instance itself. The types of events are
 * described in the {@link EventType} enumeration.
 * <p>
 * Events are generated by the {@code Game} instance through its methods, that
 * are likeley to be called by other classes interacting with the {@code Game}.
 * These classes may be other {@code GameListener} subtypes.
 * <p>
 * NOTE: {@code GameListener} instances are "Views" of the Model-View-Controller
 * pattern used to design this project.
 * 
 * @see Game
 * @see EventType
 */
public interface GameListener {

    /**
     * Updates this {@code GameListener} according to a given {@code GameEvent}.
     * <p>
     * This method is most likely to be called by a {@code Game} instance.
     * 
     * @param event Event to react on, as a {@code GameEvent} object.
     * @see GameEvent
     */
    void update(GameEvent event);

    /**
     * Sets the {@code Game} instance to read information on.
     * <p>
     * Listeners may need to be aware of the state of a {@code Game} object to
     * update themselves properly, e.g. if it is a graphical user interface or a
     * terminal user interface displaying a {@code Game}.
     * 
     * @param game The {@code Game} instance to read information on.
     * @see Game
     */
    void setGame(Game game);

    /**
     * Sets the {@code GameController} to interact with.
     * <p>
     * Listeners may be the support of components the user can interact with to
     * control a {@code Game} object, e.g. a graphical user interface using buttons.
     * These components are provided by the {@code GameController} object.
     * 
     * @param controller The {@code GameController} instance whose methods can be
     *                   called to interact with the user.
     * @see GameController
     */
    void setController(GameController controller);

}